# this is only to see if the DEFAULT-CONFIG-LATEST.YML updates...
plugin-version: 1.5.4

############################################################
# +------------------------------------------------------+ #
# |                     Settings                         | #
# +------------------------------------------------------+ #
############################################################

settings:
  default-tag: 'none' # set 'none' players start with no tag.
  forced-tag: false # this will make it force players to have a tag, they won't beable to take the tag off.
  categories: false # should supremetags use the category system?
  default-category: 'default' # used to set the tags category value when creating a new tag with the '/tag create' command
  layout: 'layout1' # layouts: [layout1(default), layout2(new)]
  update-check: true # the plugin will check if there is an update available.
  legacy-hex-format: true # should the plugin use the legacy hex colors? (&#d5b47 instead of #d5b47)
  auto-merge: false # auto merges all tags from deluxetags into supremetags (DeluxeTags is required on the server)
  active-tag-glow: true # adds a hidden enchantment to the tag item that is active for the player.
  cost-system: false # should your players be able to buy tags?

############################################################
# +------------------------------------------------------+ #
# |                       Data                           | #
# +------------------------------------------------------+ #
############################################################

# mysql data settings.
# make sure you can check your panel database info to make sure everything is correct.
data:
  # types: [H2 OR MYSQL]
  type: 'H2'

  # The address for the database server.
  # - to enable this part, change type to 'MYSQL'
  # - some hosts can use your domain or server ip.
  address: 'host'
  # The standard DB engine port is used by default
  port: 3306
  # The name of the database to store tag data in.
  database: 'database'
  # Credentials for the database.
  username: 'user'
  password: 'pass'
  # leave this, if you don't know how to use options.
  options: 'useSSL=false&autoReconnect=true'

############################################################
# +------------------------------------------------------+ #
# |                       Gui                            | #
# +------------------------------------------------------+ #
############################################################

gui:
  main-menu:
    title: '&8Main Menu'
    size: 27
  tag-menu-none-categories:
    title: '&8Tag Menu'
    tag-item:
      displayname: '&7Tag: %tag%'
      lore:
        - '&7&m-----------------------------'
        - ''
        - '&bIdentifier: &7%identifier%'
        - ''
        - '&dDescription:'
        - '&7%description%'
        - ''
        - '&eClick to Assign!'
        - '&7&m-----------------------------'
      locked-lore:
        - '&c&m-----------------------------'
        - ''
        - '&7Buy &8&l> &fRight-Click'
        - '&7Cost &8&l> &f$%cost%'
        - ''
        - '&cThis tag is locked!'
        - '&c&m-----------------------------'
      unlocked-lore:
        - '&7&m-----------------------------'
        - ''
        - '&bIdentifier: &7%identifier%'
        - ''
        - '&dDescription:'
        - '&7%description%'
        - ''
        - '&eClick to Assign!'
        - '&7&m-----------------------------'
  layout:
    glass-material: 'GRAY_STAINED_GLASS_PANE'
    tag-material: 'NAME_TAG'
    back-next-material: 'DARK_OAK_BUTTON'
    reset-tag-material: 'RED_DYE'
    close-menu-material: 'BARRIER'
    create-tag-material: 'NAME_TAG'
    refresh-material: 'GREEN_DYE'

############################################################
# +------------------------------------------------------+ #
# |                    Categories                        | #
# +------------------------------------------------------+ #
############################################################

categories:
  default:
    title: '&8Default Tags (Page %page%)' # title of the category gui.
    material: 'NAME_TAG' # item material.
    id_display: '&7&lDefault Tags' # item displayname.
    slot: 11 # slot this item will be in the main menu.
    lore:
      - '&8&m-----------------------------'
      - ''
      - '&7Default tags: &7%tags_amount%'
      - ''
      - '&8&m-----------------------------'
    permission: 'supremetags.category.default' # permission players will need to open this menu
    permission-see-category: false # if set true and if player doesn't have the permission `supremetags.category.<category>` they will not see it.
  rank:
    title: '&8Rank Tags (Page %page%)' # title of the category gui.
    material: 'NAME_TAG' # item material.
    id_display: '&6&lRank Tags' # item displayname.
    slot: 13 # slot this item will be in the main menu.
    lore:
      - '&8&m-----------------------------'
      - ''
      - '&6Rank tags: &7%tags_amount%'
      - ''
      - '&8&m-----------------------------'
    permission: 'supremetags.category.rank' # permission players will need to open this menu
    permission-see-category: false # if set true and if player doesn't have the permission `supremetags.category.<category>` they will not see it.
  xmas:
    title: '&8Christmas Tags (Page %page%)' # title of the category gui.
    material: 'NAME_TAG' # item material.
    id_display: '&c&lChristmas Tags' # item displayname.
    slot: 15 # slot this item will be in the main menu.
    lore:
      - '&8&m-----------------------------'
      - ''
      - '&cChristmas tags: &7%tags_amount%'
      - ''
      - '&8&m-----------------------------'
    permission: 'supremetags.category.xmas' # permission players will need to open this menu
    permission-see-category: false # if set true and if player doesn't have the permission `supremetags.category.<category>` they will not see it.
############################################################
# +------------------------------------------------------+ #
# |                       Tags                           | #
# +------------------------------------------------------+ #
############################################################

tags:
  hexsupport: # 1.16+ server is required for hex colors to work.
    tag: '&8[&#afe4a4&lH&#b1cdb1&le&#b3b6bd&lx&#b59fca&lC&#b688d7&lo&#b871e3&ll&#ba5af0&lo&#bc43fd&lr&8]'
    permission: 'supremetags.tag.hex'
    description: '&7This plugin supports normal/hex colors'
    category: 'default'
    displayname: '&7Tag: %tag%'
    display-item: 'NAME_TAG'
    cost: 200 # this is only implemented when 'cost-system' is enabled.
  santa: # Christmas themed tag, shows in the Xmas category.
    tag: '&8[&c&lSanta&8]'
    permission: 'supremetags.tag.santa'
    description: '&7ho ho hooooooo!'
    category: 'xmas'
    displayname: '&7Tag: %tag%'
    display-item: 'NAME_TAG'
    cost: 100 # setting this to 0 when 'cost-system' is enabled, will make this tag free.