name: SupremeTags
version: '${project.version}'
main: net.noscape.project.supremetags.SupremeTags
api-version: 1.13
softdepend: [PlaceholderAPI]
authors: [NoScape]
description: Allow player to show of their supreme tags!

commands:
  tags:
    aliases: [tag, supremetags, stags]
    description: main tag plugin to open menu and manage tags.